import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Header from "@/components/Header";
import Loading from "@/components/Loading";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${inter.variable} antialiased`}>
				<ThemeProvider attribute="class">
					<TooltipProvider>
						<div className="flex h-full flex-col">
							<Header />

							<Suspense fallback={<Loading />}>
								<main className="h-full">{children}</main>
							</Suspense>
						</div>
					</TooltipProvider>
				</ThemeProvider>

				<Toaster richColors />
			</body>
		</html>
	);
}
